### PR TITLE
Implement without constructors

### PR DESCRIPTION
**Pull request by hanshoglund**

### CODE REVIEW

**Comment by garyb** [comment]
I like the idea of doing it this way, but we should probably benchmark to ensure it's at least as fast as the original. I no longer have any idea how JS will behave with differences like these. :wink:

**Comment by paf31** [comment]
I wouldn't be surprised if the `delete this.thunk` was important somehow.

**Comment by garyb** [comment]
Maybe, but if we can avoid it it porbably would be better - `delete` is generally Bad in JS, as it prevents any kind of "hidden class" optimisations. Setting to undefined is better unless `hasOwnProperty` is being used for the presence test.

**Comment by garyb** [comment]
The question really is whether using closure scope or object properties are faster.

**Comment by paf31** [comment]
Perhaps we could do a performance comparison.

**Comment by matthewleon** [comment]
I have done this:

performance profile on master: https://github.com/matthewleon/purescript-lazy/tree/profile
performance profile with this change: https://github.com/matthewleon/purescript-lazy/tree/constructorless-profile

The test is a profile of the following two lines:
```purescript
let longList = L.range 1 1000000
    len = L.length longList
```

On Chrome 56.0.2924.110 (64-bit):
master version runs in ~1.8s. More than half that time is spent in staggered GC pauses.
constructor-free version runs in ~13s (about 7x as slow):. Seems more than 90% of the time spent in GC pauses.

Don't know enough about V8 garbage collection to understand what, exactly, is happening in either case, given that the forced thunks shouldn't be removed from memory. Perhaps they are being shifted from one GC zone to another? Would love some insight.

Pics:

screenshot 2017-03-22 at 5 07 36 pm
screenshot 2017-03-22 at 5 08 55 pm

**Comment by matthewleon** [comment]
On further thought, I came to the idea that what makes the GC stutter so much might be that the closure's reference to `thunk` is leaking. The browser GC probably isn't smart enough to know that the `else` clause will never be triggered again, and thus retains the reference to `thunk` even after it has been called.

**Comment by matthewleon** [comment]
@garyb this should be closed by #21

**Pull request closed without merging**
