### PR TITLE
refactor using applicative combinators

### PR DESCRIPTION
**Pull request by safareli**

### CODE REVIEW

**Comment by safareli** [comment]
If desired `eq` and `compare` could be rewritten as:

```diff
-eq x y = (force x) == (force y)
+eq x y = force $ eq <$> x <*> y

-compare x y = compare (force x) (force y)
+compare x y = force $ compare <$> x <*> y
```

**Comment by paf31** [comment]
We'd need to measure the performance impact of these changes in the absence of inlining.

**Comment by safareli** [comment]
Ah I see, if we measure refactored version, changes like this will have no performance changes:
```diff
-foo = defer \_ -> x
+foo = pure x
```

but this:
```diff
-  foo a b = defer \_ -> force a `foo` force b
+ foo a b = foo <$> a <*> b
```

will be slower as it will desugar to:

```hs
defer \_ -> force (defer \_ -> foo $ force a) $ force b
```

which requires more wrapping/unwrapping

**Comment by paf31** [comment]
This is still potentially an anti-optimization if the evaluation of the thing under the lambda is expensive. That's possible if, for example, evaluating `zero` involves several type class dictionary lookups.

**Comment by safareli** [comment]
OK will close it then

**Pull request closed without merging**
